apiVersion: apps/v1
kind: Deployment
metadata:
  name: akulaku
  namespace: akulaku
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: akulaku
  template:
    metadata:
      labels:
        app: akulaku
    spec:
      containers:
      - name: akulaku
        image: riqimaruq/akulaku:latest
        ports:
        - name: web
          containerPort: 80
