apiVersion: apps/v1
kind: Deployment
metadata:
  name: akulaku
  namespace: aplikasi
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: akulaku
  template:
    metadata:apiVersion: apps/v1
kind: Deployment
metadata:
  name: akulaku
  namespace: aplikasi
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: akulaku
  template:
    metadata:
      labels:
        app: akulaku
    spec:
      containers:
      - name: akulaku
        image: riqimaruq/akulaku:latest
        resources:
          limits:
            memory: 100Mi
        ports:
        - name: web
          containerPort: 80
      automountServiceAccountToken: false
      labels:
        app: akulaku
    spec:
      containers:
      - name: akulaku
        image: riqimaruq/akulaku:latest
        resources:
          limits:
            memory: 100Mi
        ports:
        - name: web
          containerPort: 80
      automountServiceAccountToken: false
