apiVersion: v1
kind: Service
metadata:
  name: akulaku
  namespace: aplikasi
  labels:
    app: akulaku
spec:
  type: LoadBalancer
  ports:
  - name:  http
    port:  80
    targetPort: 80
    protocol: TCP
  selector:
    app: akulaku
